blank_issues_enabled: false
contact_links:
  - name: Have questions about orangefox builder?
    url: https://wiki.orangefox.tech/en/dev/building
    about: "(o゜▽゜)o☆ You can read it on the github wiki or read the doc. It would be even better if you could give the repository a star!"
