name: OrangeFox - Build - Test

on:
  workflow_dispatch:

jobs:
  build:
    name: 🦊 Building OrangeFox Recovery
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4
              
    - name: OrangeFox Build
      uses: ./
      with:
        FOX_SYNC_BRANCH: '12.1'
        DEVICE_TREE: 'https://github.com/UntuKemeng/ORF_device_vivo_1938'
        DEVICE_TREE_BRANCH: '12.1'
        DEVICE_PATH: 'device/vivo/1938'
        DEVICE_NAME: '1938'
        BUILD_TARGET: 'recovery'
        TG_CHAT_ID: '${{ secrets.TG_CHAT_ID }}'
        TG_TOKEN: '${{ secrets.TG_TOKEN }}'
        MAINTAINER_URL: 'https://i.ibb.co.com/8gyjXq06/maintainer.png'
        GH_RELEASE: 'false'
